name: Installation Dry Run

on:
  pull_request:
    branches: [ "main" ]

jobs:
  dry-run:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Run setup script from PR
      run: |
        set -e
        echo "Starting dry run installation process..."

        # Get the PR branch name
        BRANCH_NAME=${GITHUB_HEAD_REF}
        echo "PR branch: ${BRANCH_NAME}"

        # Get the PR repo
        REPO_URL="https://github.com/${GITHUB_REPOSITORY}"
        REPO_RAW_URL="https://raw.githubusercontent.com/${GITHUB_REPOSITORY}"
        echo "PR repository: ${REPO_URL}"

        # Download the setup script from the PR's branch
        echo "Downloading setup script..."
        curl -s "${REPO_RAW_URL}/${BRANCH_NAME}/setup.sh" -o setup.sh
        if [ ! -f setup.sh ]; then
          echo "Error: Failed to download setup.sh"
          exit 1
        fi

        echo "Checking if setup.sh was downloaded correctly:"
        ls -l setup.sh

        # Modify the setup script to use the PR's branch/repo
        echo "Modifying setup script..."
        sed -i "s|git clone https://github.com/icewatch-io/icebox.git|git clone -b ${BRANCH_NAME} ${REPO_URL}|g" setup.sh

        # Run the setup script
        echo "Running setup script..."
        chmod +x setup.sh
        sudo bash -x setup.sh 2>&1

        # Verify the service was installed
        echo "Verifying service installation..."
        if systemctl is-active icebox; then
          echo "Installation successful: icebox service is active"
        else
          echo "Error: icebox service is not active"
          exit 1
        fi